[project]
name = "basic-harness"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "docker>=7.1.0",
    "langfuse>=4.13.1",
    "pydantic-ai-slim[google,openai]>=2.6.0",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "pydantic-ai-slim[web]>=2.6.0",
    "pydantic-monty>=0.0.18",
]
